name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^16
      - run: npm ci
      - run: npm run compile
      - run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^16
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run compile
      - run: npm test
      - run: npx lerna@4.0.0 publish from-git -y --no-verify-access --dist-tag=next
        if: "contains(github.ref, '-pre.')"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npx lerna@4.0.0 publish from-git -y --no-verify-access
        if: "!contains(github.ref, '-pre.')"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
